kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mongo-qa
  namespace: default
  resourceVersion: '2105656'
  generation: 1
  labels:
    app: mongo-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-qa
  template:
    metadata:
      labels:
        app: mongo-qa
    spec:
      containers:
        - name: mongo-qa
          image: 'acrjdtest.azurecr.io/mongo:latest'
          ports:
            - containerPort: 27017
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: my-secret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
---
kind: Service
apiVersion: v1
metadata:
  name: mongo-qa
  namespace: default
  resourceVersion: '2105960'
spec:
  ports:
    - name: http1
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-qa
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demochat-qa
  namespace: default
  resourceVersion: '2106094'
  generation: 1
  labels:
    app: demochat-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demochat-qa
  template:
    metadata:
      labels:
        app: demochat-qa
    spec:
      containers:
        - name: demochat-qa
          image: 'acrjdtest.azurecr.io/demochat:latest'
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: my-secret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
---
kind: Service
apiVersion: v1
metadata:
  name: demochat-qa
  namespace: default
spec:
  ports:
    - name: http1
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: demochat-qa
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
